/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminCollaborationsRouteImport } from './routes/admin.collaborations'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCreatorsRouteImport } from './routes/admin.creators'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BrandApplicantsRouteImport } from './routes/brand.applicants'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CollaborationsIndexRouteImport } from './routes/collaborations.index'
import { Route as CollaborationsCollabIdRouteImport } from './routes/collaborations.$collabId'
import { Route as BrandCampaignsIndexRouteImport } from './routes/brand.campaigns.index'
import { Route as BrandCampaignsNewRouteImport } from './routes/brand.campaigns.new'
import { Route as CampaignsCampaignIdIndexRouteImport } from './routes/campaigns.$campaignId.index'
import { Route as CampaignsCampaignIdApplyRouteImport } from './routes/campaigns_.$campaignId.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/admin/brands',
  path: '/admin/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaborationsRoute = AdminCollaborationsRouteImport.update({
  id: '/admin/collaborations',
  path: '/admin/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreatorsRoute = AdminCreatorsRouteImport.update({
  id: '/admin/creators',
  path: '/admin/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/admin/disputes',
  path: '/admin/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const BrandApplicantsRoute = BrandApplicantsRouteImport.update({
  id: '/brand/applicants',
  path: '/brand/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsIndexRoute = CollaborationsIndexRouteImport.update({
  id: '/collaborations/',
  path: '/collaborations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsCollabIdRoute = CollaborationsCollabIdRouteImport.update({
  id: '/collaborations/$collabId',
  path: '/collaborations/$collabId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsIndexRoute = BrandCampaignsIndexRouteImport.update({
  id: '/brand/campaigns/',
  path: '/brand/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsNewRoute = BrandCampaignsNewRouteImport.update({
  id: '/brand/campaigns/new',
  path: '/brand/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdIndexRoute =
  CampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdApplyRoute =
  CampaignsCampaignIdApplyRouteImport.update({
    id: '/campaigns_/$campaignId/apply',
    path: '/campaigns/$campaignId/apply',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/collaborations': typeof AdminCollaborationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brand/applicants': typeof BrandApplicantsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/collaborations/$collabId': typeof CollaborationsCollabIdRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/collaborations/': typeof CollaborationsIndexRoute
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/brand/campaigns/': typeof BrandCampaignsIndexRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/collaborations': typeof AdminCollaborationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brand/applicants': typeof BrandApplicantsRoute
  '/collaborations/$collabId': typeof CollaborationsCollabIdRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/collaborations': typeof CollaborationsIndexRoute
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/brand/campaigns': typeof BrandCampaignsIndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/collaborations': typeof AdminCollaborationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brand/applicants': typeof BrandApplicantsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/collaborations/$collabId': typeof CollaborationsCollabIdRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/collaborations/': typeof CollaborationsIndexRoute
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
  '/campaigns_/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/brand/campaigns/': typeof BrandCampaignsIndexRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/collaborations'
    | '/admin/content'
    | '/admin/creators'
    | '/admin/disputes'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/auth/callback'
    | '/brand/applicants'
    | '/campaigns/$campaignId'
    | '/collaborations/$collabId'
    | '/admin/'
    | '/campaigns/'
    | '/collaborations/'
    | '/brand/campaigns/new'
    | '/campaigns/$campaignId/apply'
    | '/brand/campaigns/'
    | '/campaigns/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/collaborations'
    | '/admin/content'
    | '/admin/creators'
    | '/admin/disputes'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/auth/callback'
    | '/brand/applicants'
    | '/collaborations/$collabId'
    | '/admin'
    | '/campaigns'
    | '/collaborations'
    | '/brand/campaigns/new'
    | '/campaigns/$campaignId/apply'
    | '/brand/campaigns'
    | '/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/collaborations'
    | '/admin/content'
    | '/admin/creators'
    | '/admin/disputes'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/auth/callback'
    | '/brand/applicants'
    | '/campaigns/$campaignId'
    | '/collaborations/$collabId'
    | '/admin/'
    | '/campaigns/'
    | '/collaborations/'
    | '/brand/campaigns/new'
    | '/campaigns_/$campaignId/apply'
    | '/brand/campaigns/'
    | '/campaigns/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCollaborationsRoute: typeof AdminCollaborationsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCreatorsRoute: typeof AdminCreatorsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  BrandApplicantsRoute: typeof BrandApplicantsRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CollaborationsCollabIdRoute: typeof CollaborationsCollabIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CollaborationsIndexRoute: typeof CollaborationsIndexRoute
  BrandCampaignsNewRoute: typeof BrandCampaignsNewRoute
  CampaignsCampaignIdApplyRoute: typeof CampaignsCampaignIdApplyRoute
  BrandCampaignsIndexRoute: typeof BrandCampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collaborations': {
      id: '/admin/collaborations'
      path: '/admin/collaborations'
      fullPath: '/admin/collaborations'
      preLoaderRoute: typeof AdminCollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/creators': {
      id: '/admin/creators'
      path: '/admin/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AdminCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/brand/applicants': {
      id: '/brand/applicants'
      path: '/brand/applicants'
      fullPath: '/brand/applicants'
      preLoaderRoute: typeof BrandApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/': {
      id: '/collaborations/'
      path: '/collaborations'
      fullPath: '/collaborations/'
      preLoaderRoute: typeof CollaborationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/$collabId': {
      id: '/collaborations/$collabId'
      path: '/collaborations/$collabId'
      fullPath: '/collaborations/$collabId'
      preLoaderRoute: typeof CollaborationsCollabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/': {
      id: '/brand/campaigns/'
      path: '/brand/campaigns'
      fullPath: '/brand/campaigns/'
      preLoaderRoute: typeof BrandCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/new': {
      id: '/brand/campaigns/new'
      path: '/brand/campaigns/new'
      fullPath: '/brand/campaigns/new'
      preLoaderRoute: typeof BrandCampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof CampaignsCampaignIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns_/$campaignId/apply': {
      id: '/campaigns_/$campaignId/apply'
      path: '/campaigns/$campaignId/apply'
      fullPath: '/campaigns/$campaignId/apply'
      preLoaderRoute: typeof CampaignsCampaignIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCollaborationsRoute: AdminCollaborationsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCreatorsRoute: AdminCreatorsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  BrandApplicantsRoute: BrandApplicantsRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CollaborationsCollabIdRoute: CollaborationsCollabIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CollaborationsIndexRoute: CollaborationsIndexRoute,
  BrandCampaignsNewRoute: BrandCampaignsNewRoute,
  CampaignsCampaignIdApplyRoute: CampaignsCampaignIdApplyRoute,
  BrandCampaignsIndexRoute: BrandCampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
